language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23

before_install:
 - chmod +x ./gradlew
 #updates permissions for travis

#notifications:
  #slack: grouplock:dTkArNoCUeyRITfhTUwQAuBX
  
   #push the build
