language: objective-c
osx_image: xcode7.3
install:
  - brew update
  - brew reinstall nvm xctool

xcode_workspace: GroupLock iOS/GroupLock.xcworkspace
xcode_scheme: GroupLock 
xcode_sdk: iphonesimulator9.3
