language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23

script:
   - ./GroupLockApplication/gradlew build connectedCheck

notifications:
  slack: grouplock:dTkArNoCUeyRITfhTUwQAuBX
  
   #push the build
