source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

def shared_pods
    pod 'NUI', :git => 'https://github.com/broadwaylamb/nui.git', :branch => 'grouplock'
    pod 'JSQDataSourcesKit'
    pod 'JSQCoreDataKit'
    pod 'Agrume', :git => 'https://github.com/JanGorman/Agrume.git'
end

target 'GroupLock' do
    shared_pods
end

target 'GroupLockTests' do
    shared_pods
end
