source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def shared_pods
    pod 'NUI', :git => 'https://github.com/broadwaylamb/nui.git', :branch => 'grouplock'
    pod 'JSQDataSourcesKit'
end

target 'GroupLock' do
    shared_pods
end

target 'GroupLockTests' do
    shared_pods
end
